platform :ios, '9.3'
inhibit_all_warnings!
use_frameworks!

target 'SmartLog' do
    
    pod 'PebbleKit', '~> 3.1.1'
    
    pod 'Charts/Core', '~> 3.0.2'
    pod 'CoreStore', '~> 4.0.5'
    
    pod 'Dip', '~> 5.0.1'

    pod 'Fabric', '~> 1.6.8'
    pod 'Crashlytics', '~> 3.8.0'

end
